### ISSUE TITLE
False error

### ISSUE THREAD

**Issue by PLyczkowski** [GodotExplorer/godot-tools#12]
I get this marked as error:

https://dl.dropboxusercontent.com/s/udr4vsx1nz6dogn/shot_170323_170407.png

**Comment by PLyczkowski** [comment]
Everything seems to be indented correctly here, and the code runs no problem.

https://dl.dropboxusercontent.com/s/k1po10iq89dc6wl/shot_170323_170745.png

**Comment by Geequlim** [comment]
Please put images inside the github issue page thanks.
