### ISSUE TITLE
Colors bug

### ISSUE THREAD

**Issue by PLyczkowski** [GodotExplorer/godot-tools#13]
Something went wrong with colors here:

https://dl.dropboxusercontent.com/s/5l3m6sk7vio5pu0/shot_170324_140847.png

**Comment by Geequlim** [comment]
Which syntax theme can show colored parameters in VSCode?

**Comment by PLyczkowski** [comment]
You can check python I guess?

**Comment by Geequlim** [comment]
Fixed.
The parameters now with color highlight and also the default values.
