### ISSUE TITLE
line continuation does not get recognized

### ISSUE THREAD

**Issue by shawniac** [GodotExplorer/godot-tools#15]
The following is *valid* GDScript, at least it works in the engine itself with no complaints, but gets highlighted as an error. (see **Line 64** and **Line 71**)

Screenshot:
![31_03_2017](https://cloud.githubusercontent.com/assets/1819638/24541343/5abfbd50-15f7-11e7-84f5-b2ec83ce4543.png)

**Comment by Geequlim** [comment]
I have no idea about this :(

**Comment by Geequlim** [comment]
Fixed.
Thanks
