### ISSUE TITLE
Methods and variable appear twice

### ISSUE THREAD

**Issue by NathanLovato** [GodotExplorer/godot-tools#2]
The definition for user created methods and variables is always shown at least 2 times, when the method/variable is only defined once:

![image](https://cloud.githubusercontent.com/assets/12694995/21840369/6d667262-d7dd-11e6-9ce7-6edb89b7e2f6.png)

**Comment by Geequlim** [comment]
How can I reproduce that?

**Comment by NathanLovato** [comment]
I don't know how to reproduce it, I have that issue on every Godot file.

**Comment by Geequlim** [comment]
The problem on Windows should be sovled from version 0.2.0 :)

**Comment by NathanLovato** [comment]
Confirmed, it's solved. Thank you :)
