### ISSUE TITLE
[proposal] new icon based on Godot 3.0

### ISSUE THREAD

**Issue by stephdin** [GodotExplorer/godot-tools#26]
I quickly created a new icon, based on the one from Godot 3.0.
Glasses are from [iconmonstr](https://iconmonstr.com/?s=glasses)

![new_icon](https://cloud.githubusercontent.com/assets/13117706/26499569/7221e60e-4233-11e7-907f-06754e675857.png)

what do you think? :)

**Comment by Geequlim** [comment]
cool
