### ISSUE TITLE
Error when using comment on line after function declaration

### ISSUE THREAD

**Issue by Willowblade** [GodotExplorer/godot-tools#28]
If I'd write this:

def derp():
    pass # replace later

Which is generated by connecting signals in the editor to scripts, the extension sees this as an error in the code analysis while it shouldn't be, mistaking it for this behaviour:

def derp():
    # replace later

**Comment by Geequlim** [comment]
We should put comments upon the function declaration the plugin will generate workspace document for you.

**Comment by Geequlim** [comment]
I think this is already fix.
