### ISSUE TITLE
Enhancement: Indentation rules

### ISSUE THREAD

**Issue by PLyczkowski** [GodotExplorer/godot-tools#29]
VSCode now has auto indentation support, but this needs indentation rules per language to work:

![image](https://user-images.githubusercontent.com/7307968/28370850-ac4f95c8-6c9b-11e7-9c09-b976414adcb2.png)

**Comment by Geequlim** [comment]
Thanks

**Comment by Geequlim** [comment]
How can I get more informations about this?

**Comment by Geequlim** [comment]
This feature will be avaliable with next release with VSCode 1.9.1 and later
