### ISSUE TITLE
Duplicate definitions for built-in methods

### ISSUE THREAD

**Issue by NathanLovato** [GodotExplorer/godot-tools#3]
Builtin methods like _ready, _fixed_process etc. are indexed in the whole workspace. I think it would be more useful to only have the engine's built-in definition, so you can access the documentation easily. The current implementation makes it harder to find the information you're looking for (the screenshot is for a small project - with a large godot game, it's going to be worse). 

I would suggest 2 options:
- Don't index the symbol when it's a built-in method
- Or only add the definition once and leave "Click to show 8 definitions"

![image](https://cloud.githubusercontent.com/assets/12694995/21840425/c2433572-d7dd-11e6-8017-3d1829525080.png)

**Comment by Geequlim** [comment]
Thanks for your remand.
I will reorder the tips instead of remove them for the case we need to check `Where we overrided the function _read()` via mouse hover.

BTW. How did your VSCode can show the tip `Click to Show 8 definitions`?

**Comment by NathanLovato** [comment]
Ah yes, having the source/engine definition at the top would probably solve it.
```Click to Show 8 definitions``` is here by default. It doesn't show on your computer?

**Comment by Geequlim** [comment]
Yes the top tip seems clickable is never appeared on my machines
