### ISSUE TITLE
Intellisense not loading for .gd files

### ISSUE THREAD

**Issue by somkun** [GodotExplorer/godot-tools#34]
Plugin Version: 0.2.9
VSCode Version: 1.14.2

I get syntax highlighting, but [CTRL+SPACE] produces only templates, not functions.

**Comment by somkun** [comment]
[Link to screenshot](https://1drv.ms/i/s!AilbJ1ACawWc5UhJaFouvYhwbrhS)

**Comment by Geequlim** [comment]
You should save your script first.
If it doen't work after save script please try to run command `godot.updateWorkspaceSymbo` or reload the project window.

![image](https://user-images.githubusercontent.com/6964556/29155117-55d47000-7dcc-11e7-914c-e6e1ee4dc45d.png)

**Comment by somkun** [comment]
running "Update Workspace Symbols" fixed it. This should probably be in the documentations somewhere.

**Comment by Geequlim** [comment]
@somkun Update the readme document is welcome as it is hard for me of the poor english
