### ISSUE TITLE
pass keyword autocompletion

### ISSUE THREAD

**Issue by adamrej** [GodotExplorer/godot-tools#36]
Hi,

Great work on this toolset, thanks for your hard work.

When typing pass in an empty function/code block the autocomplete doesn't suggest pass and typing pass + [Enter] will give you something you then have to delete.

Could you add pass to the autocomplete dictionary please?

Thanks

Adam

**Comment by Geequlim** [comment]
Of couse

**Comment by Geequlim** [comment]
I will add it as a sinnipet instead of a completion item.

**Comment by Geequlim** [comment]
Is the problem fixed with latest version of the plugin?

**Comment by adamrej** [comment]
Thanks Dude, that's done the business.

:)
