### ISSUE TITLE
Expected indented by "comments"

### ISSUE THREAD

**Issue by Shockblast** [GodotExplorer/godot-tools#39]
sorry my english
if I deleted the comment 2 the keyword disappears.
![ss](https://user-images.githubusercontent.com/5357217/30000973-75b995ee-9055-11e7-9211-4e6acdade208.png)

**Comment by endragor** [comment]
Another sample that also results in that error:
```
func do_something():
  pass # replace with function body
```

**Comment by Geequlim** [comment]
Fixed with 27d7501672e484042
