### ISSUE TITLE
Deprecation - use MarkdownString for command-links

### ISSUE THREAD

**Issue by jrieken** [GodotExplorer/godot-tools#40]
This extension has been identified as using command-links in either hovers or decorations. The August release (1.16) is the last release to support this in the `MarkedString` and with September the `MarkdownString` must be used. We are doing this because of security concerns. Background and details are explained here: https://github.com/Microsoft/vscode/issues/33577#issue-254264186

The adoption should be straight forward and usages of `MarkedString` need to be replaced with: 

```
let md = new MarkdownString(content);
md.isTrusted = true;
```

Please let us know if you need more information. Thanks and Happy Coding

**Comment by jrieken** [comment]
ping - the change will happen soon

**Comment by Geequlim** [comment]
@jrieken  Thanks for your remind.
