### ISSUE TITLE
Valid for-loop considered invalid

### ISSUE THREAD

**Issue by endragor** [GodotExplorer/godot-tools#43]
```gdscript
func iterate():
  for i in (50):
    pass
```
This results in error: `Invalid for expression`. Removing parens from the expression clears the error:
```gdscript
func iterate():
  for i in 50:
    pass
```

**Comment by Geequlim** [comment]
Is `for i in 50:` a valid syntax in GDScript ?
I never used this kind of statement 😆

**Comment by endragor** [comment]
It's certainly a valid _syntax_ (which is `'for' ident 'in' expr`). The problem is that wrapping something into parens makes it not an expression anymore, which is a bug. The same problem can be seen with:
```gdscript
for i in ("Hello"):
  pass
```

```gdscript
for i in (dict):
  pass
```
