### ISSUE TITLE
Autocompletions and definitions not working

### ISSUE THREAD

**Issue by tdheff** [GodotExplorer/godot-tools#44]
On VSCode version 1.7.1, and no auto-completions seem to be working. I don't get them while typing, and `ctrl+space` gives me the message about not finding them. Hovering doesn't work either. Snippets working correctly, though.

**Comment by Geequlim** [comment]
try run update workspace symbols

2017年10月16日 10:29，"Tommy Heffernan" <notifications@github.com>写道：

**Comment by Geequlim** [comment]
Oh this is a new bug

**Comment by mfdeveloper** [comment]
Hello @Geequlim !! I'ven got the same problem today. The autocomplete is not working. I tried run `GodotTools: Update workspa symbols` but nothing happens :(

Can you reopen this issue? @tdheff solve the autocomplete problem?

**Comment by Geequlim** [comment]
@mfdeveloper  This problem is solved by edcb8b9  please wait the next release.
Befor the next release you can set the `GodotTools.godotVersion` to `3.0` and reload the vscode window.

**Comment by mfdeveloper** [comment]
@Geequlim Thanks a lot for your instructions! I did the steps below:

1. Download the zip file from the **[master]** branch, 
2. Extract their files with your last commits into your **VSCode extensions dir** (commonly `.vscode/extensions/[author.plugin_name-version]`,
3. Change the `godotVersion` **vscode** settings to `3.0`like you said

And it works! 😄
