### ISSUE TITLE
Allow disabling syntax checking rules

### ISSUE THREAD

**Issue by Lucrecious** [GodotExplorer/godot-tools#48]
I like writing code my own way, like using brackets in if statements for example, even when they aren't needed.

It'd be nice to be able to disable some of these rules or even all of them.

I don't think there's a way to do it with the current settings, am I missing something?

Also, I've added the extension from the extension manager in VSCode, but I still get warnings for inlined if else statements (even though they're fixed here).

**Comment by Geequlim** [comment]
If you guys don't like that I will add an option to disable it.

**Comment by Geequlim** [comment]
You can set `GodotTools.enableSyntaxChecking` to `false` to disable syntax checking in next release.
