### ISSUE TITLE
Typo in completion.ts

### ISSUE THREAD

**Issue by Zylann** [GodotExplorer/godot-tools#50]
I know nothing about VSCode plugins, but isn't `Thenable` a typo? Shouldn't it be `Themable`?

https://github.com/GodotExplorer/godot-tools/blob/4c47fff9afbcd81694506516cfff53fc0bd01413/src/gdscript/completion.ts#L48

**Comment by Geequlim** [comment]
No it is not a typo you can reference here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve
