### ISSUE TITLE
The Exec Flags {project} --goto {file}:{line}:{col} gives error. . .

### ISSUE THREAD

**Issue by 3DMagicVR** [GodotExplorer/godot-tools#55]
Hi, I set the VS Code to be my default text editor and when I set this: {project} --goto {file}:{line}:{col}, the console drops this error:

the mode arguments from "--goto" must have format "FILE(:LINE(:CHARACTER))"

What that means?, thanks in advanced, cheers.

PD: I'm not an experienced programmer, that's why I don't understand.

**Comment by Geequlim** [comment]
The Exec Flags `{project} --goto {file}:{line}:{col}` tell the VSCode to open the `file` in `project` folder and jump to `line` if possiable.

**Comment by Geequlim** [comment]
And you have to fill the `Exec Path` with the executable path of your VSCode.
If you are on Windows if may be placed in `C:/Program Files/Microsoft VS Code/bin/code.cmd`
