### ISSUE TITLE
Ternary check against !condition gives warning.

### ISSUE THREAD

**Issue by AlansCodeLog** [GodotExplorer/godot-tools#58]
![image](https://user-images.githubusercontent.com/26168490/38469970-0f6ee72e-3b33-11e8-8ebc-912db29edd45.png)

**Comment by tperraut** [comment]
```
texture = (_mSprite if !mState else GameVars.backTheme)
```
or
```
texture = _mSprite if !mState else GameVars.backTheme
```
Prompt errors :
 `': or \' expected at end of the line.`
`Expected indented block after expression`
and
```
texture = _mSprite if mState else GameVars.backTheme
```
or
```
texture = _mSprite if not mState else GameVars.backTheme
```
don't
Thanks for your awesome work !
