### ISSUE TITLE
Cannot open Godot documentation

### ISSUE THREAD

**Issue by tperraut** [GodotExplorer/godot-tools#61]
I do not know if it comes from my editor or your code but I did not find any answer on the web:

This work fine
![capture d ecran_2018-04-04_09-13-07](https://user-images.githubusercontent.com/9951059/38723609-f1120a90-3f01-11e8-90b4-1011cf45149e.png)

But when I ctrl+clic to see the full documentation :
![capture d ecran_2018-04-13_10-01-44](https://user-images.githubusercontent.com/9951059/38723650-114018f2-3f02-11e8-82b7-8335751182c4.png)

**Comment by Geequlim** [comment]
What is the version of your VSCode and the plugin?

**Comment by tperraut** [comment]
![capture d ecran_2018-04-13_10-43-02](https://user-images.githubusercontent.com/9951059/38725463-b33cfd00-3f07-11e8-9278-343a3d18e8c0.png)
![capture d ecran_2018-04-13_10-44-05](https://user-images.githubusercontent.com/9951059/38725474-b6c4ee24-3f07-11e8-818f-7821660ed4a8.png)

**Comment by tperraut** [comment]
Just update vscode to 1.22.2 and nothing change

**Comment by tperraut** [comment]
Ok I have more info :
![capture d ecran_2018-04-13_11-26-03](https://user-images.githubusercontent.com/9951059/38727562-aa848e2a-3f0d-11e8-814a-59de17cb3fd2.png)
Here the preview does not show but if I clic (insteed of ctrl + clic on the word directly), documentation opens in a new tab:
![capture d ecran_2018-04-13_11-26-29](https://user-images.githubusercontent.com/9951059/38727622-dda79b76-3f0d-11e8-867c-5bb6b8a9c294.png)

**Comment by Geequlim** [comment]
The Ctrl+Click can go to workspace symbols if found for now.
The builtin symbols are not supported yet.

**Comment by Geequlim** [comment]
Same with #100
