### ISSUE TITLE
New Version Plan

### ISSUE THREAD

**Issue by Geequlim** [GodotExplorer/godot-tools#76]
### Language Server Protocol support for GDScript
  - [ ] Build a tool using the source code of GDScript module to parse `.gd` scripts
  - [ ] Implement GDScript language server with LSP standard support in C++ or NodeJS
  - [ ] Refact the implemention of the VSCode plugin to use the new language server

**Comment by cprn** [comment]
Hi there. Is that a separate project? Can you link it somewhere, please?

**Comment by Geequlim** [comment]
@cprn Sorry. Don't find time to do these works.

**Comment by Geequlim** [comment]
Sorry. The plan is canceled as I can't find time to implement these stuff.
