### ISSUE TITLE
"Update GDScript symbols done" notification on program open intrusive

### ISSUE THREAD

**Issue by PLyczkowski** [GodotExplorer/godot-tools#8]
"Update GDScript symbols done" notification on program open is intrusive. Can it be done in a less intrusive manner, hidden, or have an option to be hidden?

**Comment by tapir** [comment]
Bottom bar, right corner maybe? Some addons use that corner for action/messages

**Comment by tapir** [comment]
I have made a PR for this one #11

**Comment by Geequlim** [comment]
OK I will check that and make a new release as soon as possible.

**Comment by Geequlim** [comment]
Fixed with latest release
